### ISSUE TITLE
[Mac] Open link in a new tab holding cmd doesn't work

### ISSUE THREAD

**Issue by itkind** [xiaoyifang/goldendict#208]
Hi, when holding cmd and double-clicking a word, a new tab opens with the clicked word as the search term. But when clicking on a link while holding cmd, the link opens in the same window and not in a new tab.

**Comment by xiaoyifang** [comment]
is this a previous function ?
If so ,this is a regression

**Comment by itkind** [comment]
> is this a previous function ?
What do you mean by that?

**Comment by shenlebantongying** [comment]
https://github.com/xiaoyifang/goldendict/blob/181d8a5fedf9f4ef1cc53cf3998fa2fa6e69d232/articleview.cc#L2325-L2329

According to git blame, this behaviour has been existing since 2010.

Opens word in a new tab:
macOS -> Command + Double click
Linux/Winodws -> Ctrl + Doble click

Bouns: Shift + double click also do this.

This issue should be closed.

**Comment by shenlebantongying** [comment]
> But when clicking on a link while holding cmd, the link opens in the same window and not in a new tab.

I cannot duplicate this.

Click a link -> open it
Hold Command + Click a link -> open it in new tab.
