### ISSUE TITLE
mac universal package will not be maintained any more.

### ISSUE THREAD

**Issue by xiaoyifang** [xiaoyifang/goldendict#259]
as title.

the universal package depends on maclibs folder,  I intent to remove this folder in the near future.

The homebrew build package should be good enough for daily use.

**Comment by prenfic** [comment]
Feedback

Just try with the homebrew build compare to the universal build
`[6.4.2-GoldenDict_macos-11_homebrew_20230113.dmg]`
and
`[6.4.2-GoldenDict_macos-12_homebrew_20230113.dmg]`

They are relatively slow (up to 1 min) when opening but nothing different after launch

As the m1 user and probably future apple silicon user, I selfishly hope it could be there (unless the cold app launch time will less than 10 seconds)

**Comment by shenlebantongying** [comment]
I just tried. Only 1st time launch cost long time.

Subsequent launches are fast enough. @prenfic Try multiple launches to confirm this.

1st time launch will do
* Ahead-of-time compilation which should only affect 1st launch. https://support.apple.com/en-ca/guide/security/secebb113be1/web
* Various checks including talking to Apple's services 

(I don't think we can keep the per-built maclibs. Finding someone with the knowledge & tools to build them is hard. For every macOS releases, there is a chance of breaking them. Also, they will block the way since we cannot update their versions)

Github Actions will probably have arm64 mac around Q3 this year https://github.com/github/roadmap/issues/528 . A native m1 build will be possible after that.

**Comment by prenfic** [comment]
Forget to say so
Yup, exactly gentleman, just like what you said
After minutes of waiting for the first launch, the cold launch later will
be silky smooth, averagely just open up in 1 second

Regards,
Kaijian Lawrence Law
JOHOR, MY

**Comment by xiaoyifang** [comment]
https://github.com/xiaoyifang/goldendict-ng/releases/tag/v23.05.01-WuYi.230501.6c8b0c1c
will be the last release to have universal package.

**Comment by itkind** [comment]
Sorry for the noob question. Do I understand it right, that in order to run the homebrew version, we need to install `brew install qt` only and the activity monitor will show GD as an Intel application?

**Comment by xiaoyifang** [comment]
> install `brew install qt` only

no need.

> and the activity monitor will show GD as an Intel application?

I guess it is.

**Comment by itkind** [comment]
Why is in the full text search no option for the distance between words anymore like it was before?
