### ISSUE TITLE
Search for word slow than original version

### ISSUE THREAD

**Issue by leanhtai01** [xiaoyifang/goldendict#28]
It take 1-2 seconds to display result.
In original version, the result display almost immediately.
Any suggest?

**Comment by xiaoyifang** [comment]
do you use any website dictionary ,disable them first to verify again.

**Comment by leanhtai01** [comment]
I used same set of dictionaries for both versions (tried to disable all online dictionaries too). Maybe I have some problem in build step.
I build with this command on Arch Linux:
`qmake-qt5 "CONFIG+=zim_support" "CONFIG+=chinese_conversion_support" PREFIX="/usr" goldendict.pro`
`make`

**Comment by xiaoyifang** [comment]
CONFIG+=release

can not be sure.

**Comment by xiaoyifang** [comment]
gd will wait for the dictionary to finish search before it displays the result ,if your search is always takes 1~2 seconds ,it usually mean one of your dictionary is slow.  website dictionary or wiki dictionary is mainly the cause.

**Comment by cinkohiso** [comment]
Same problem here. There is an obvious lag between the search action and showing of dictionary entries.

The problem does not occur on the official build ( which depends on Qt5Webkit) with same dictionaries and config files. Apparently the issue is not related to a specific dictionary. I doubt the lag happens on the phase of rendering. To verify this point I added my customized CSS style file in ~/.goldendict/styles/. Then I found the lag became longer.
