### ISSUE TITLE
feature: darkmode ,darkreader,custom style refinement

### ISSUE THREAD

**Issue by xiaoyifang** [xiaoyifang/goldendict#339]
when user choose a custom style ,the background is different in the following image
![image](https://user-images.githubusercontent.com/105986/217688283-b1c186b6-1d41-4403-93d4-3fa804ed3989.png)

the above image is caused by removing the custom qt-* style.css.

This has caused some confusions. I think the combination of the darkmode ,darkreader,custom style should be considered more closely.

Such as :
1, put darkmode as a custom style in the dropdownlist(Windows only).
![image](https://user-images.githubusercontent.com/105986/217688665-2c660233-7024-48b8-b2ab-48a711c4b07b.png)
by this way,the darkmode will not conflict with custom style.
2, when user choose darkmode,
- on Windows, the darkmode and darkreader both enabled.
- on Linux,Macos 
enable darkreader when the system has enabled darkmode.
darkreader can detect system darkmode.
https://github.com/darkreader/darkreader#:~:text=//%20Enable%20when%20the%20system%20color%20scheme%20is%20dark.%0ADarkReader.auto(%7B%0A%20%20%20%20brightness%3A%20100%2C%0A%20%20%20%20contrast%3A%2090%2C%0A%20%20%20%20sepia%3A%2010%0A%7D)%3B

**Comment by xiaoyifang** [comment]
@shenlebantongying  can you check on this

**Comment by shenlebantongying** [comment]
On Linux, we shouldn't override UI's background & text colour. It looks insanely good if the user wants a global theme that is comfortable for reading. 

![image](https://user-images.githubusercontent.com/20123683/218015578-c38eee7f-cc52-4eb0-968b-5e7c265aeab5.png)

---

On windows, I have a better idea: let the user choose an arbitrary background colour rather than yellow only. It will override both article's background and the side panels' background colour.

![image](https://user-images.githubusercontent.com/20123683/218016828-9e9e0990-1054-4e66-9026-d07e79a614a9.png)

The article display style will only change the style of the widgets.

![image](https://user-images.githubusercontent.com/20123683/218016393-cf7d4193-06e2-4648-a154-656d77b3d537.png)

Pro: Satisfy all users
Con: One extra setting option :sweat_smile: 

If the dark mode is enabled, then the side panel's background colour overriding will be disabled.

If the dark reader mode is enabled, then the article view's background colour overriding will be disabled.

**Comment by xiaoyifang** [comment]
I think we should not grant users too much options.

> On windows, I have a better idea: let the user choose an arbitrary background colour rather than yellow only. It will override both article's background and the side panels' background colour.

currently we have about 6 custom styles , if implemented the above feature ,we should have too much styles .
this will make the situation worse.

> If the dark mode is enabled, then the side panel's background colour overriding will be disabled.

> If the dark reader mode is enabled, then the article view's background colour overriding will be disabled.

on Windows ,this is much better.  and dark reader mode can be remove .  it should be enabled together with darkmoder.

on Linux/Macos, darkreaer can be enabled automaticly when the system has enabled the dark mode.
which means ,the two options(darkmode ,darkreader) should not appear on Linux.

**Comment by shenlebantongying** [comment]
We shouldn't use the `auto` dark reader, because `light text on dark background` is unusable for some people with low vision.

The white text on the black background will become blurry for them. Using dark UI and light text in article view is a possible use case.

https://www.google.com/search?q=accessibility+light+text+on+dark+background

**Comment by xiaoyifang** [comment]
> The white text on the black background will become blurry for them. Using dark UI and light text in article view is a possible use case.

then ,on linux, just keep the dark reader mode.

**Comment by shenlebantongying** [comment]
To prevent dark reader mode from messing with the yellow background, We can simply append  `<style> body .gdarticle { background: white; } </style>` when the dark reader is enabled.

https://github.com/xiaoyifang/goldendict/blob/bd736d7f37a3993f92c3f3557be5a52e7386f92c/article_maker.cc#L152-L165

---

However, the "correct" solution is just one step away from using arbitrary background colour:

We will remove `body { background: yellow }` from the CSS files. When the dark reader is not used, `body .gdarticle {background: #{custom_color}}` will be appended to the CSS file.

https://github.com/xiaoyifang/goldendict/blob/bd736d7f37a3993f92c3f3557be5a52e7386f92c/article-style-st-classic.css#L7-L12

**Comment by xiaoyifang** [comment]
in screenshot ,the darkmode has not been enabled ,  a custom style has been choosen.
the custom style has stop to work.

I think 587aad14716b0421c8bdcd1f31d61eed014ccd34 can be reverted and make some minor changes to satisfy the custom style.

if custom style+darkmode ,the custom style will not applied. only apply dark mode.
if custom style has been choosen ,   custom style will take effect.

**Comment by shenlebantongying** [comment]
If we revert that, there will be glitches on mac & Linux because the old custom .css isn't complete (only some styles are applied. If the user choose another global qt theme, then some weird visual glitch will happen.).

In other words: the struggles of those issues: 

https://github.com/goldendict/goldendict/issues/719
https://github.com/goldendict/goldendict/issues/679
https://github.com/xiaoyifang/goldendict/issues/271#issue-1510215538
https://github.com/xiaoyifang/goldendict/issues/188#issuecomment-1309593039

They cannot figure out a nice solution because not all styles are set.

To avoid those glitches:

One path is to avoid theming UI elements as https://github.com/xiaoyifang/goldendict/commit/587aad14716b0421c8bdcd1f31d61eed014ccd34 did.

Another is fully theming everything like nonwill does (his version is fully blue), but this approach's maintenance cost is too high.

**Comment by xiaoyifang** [comment]
the glitches only occured when enabled dark mode.

when dark mode is not enabled ,they should also work.

**Comment by shenlebantongying** [comment]
There is no concept of "dark theme" for Linux. The theme can be any colour, like purple or green or orange.

Sample glitch of reverting the commit and using the Lingoes-blue:

![image](https://user-images.githubusercontent.com/20123683/218261655-ec264376-4df0-4d44-9d50-4161beb5f82e.png)

I think the only reasonable path is to bring them back to Windows only and do as you described.

**Comment by xiaoyifang** [comment]
> Sample glitch of reverting the commit and using the Lingoes-blue (there is no "Dark mode" involved at all):

is the screenshort taken when both darkmode and lignoes-blue been enabled?
in such a case , I think only darkmode should be applied and do not apply lingoes-blue scheme.

**Comment by xiaoyifang** [comment]
maybe the goal can be split into several steps:
1, make darkmode and custom style can work on Windows.
2, keep the linux ,macos unchanged for now before a new solution come up.

**Comment by shenlebantongying** [comment]
> There is no concept of "dark theme" for Linux.
> I kind of confused.

Linux users may use any color. The black background is only one of the possibilities. Check the screen below: I can install Green/Blue/Brown backgrounds, and they are not "dark".

In fact, the Qt's style engine on Linux is replaceable,

Such as [Kvantum](https://github.com/tsujan/Kvantum/tree/master/Kvantum) which uses SVG to theme Qt widgets, a theme is just a SVG picture.

There is also [QtCurve](https://github.com/KDE/qtcurve) which is built on top of GTK so that Qt and GTK apps look exactly the same. The theme will be determined by the user's GTK theme.

Thus, there is no concept of "dark theme" on Linux.

So, I think the the best solution for Linux users is don't hard code any colours. Just don't touch the defaults unless necessary.

![image](https://user-images.githubusercontent.com/20123683/218298798-28c6a759-96d9-41c9-be5a-45d9d927832f.png)

**Comment by xiaoyifang** [comment]
> So, I think the the best solution for Linux users is don't hard code any colours. Just don't touch the defaults unless necessary

Does this mean  on linux the custom style  can be removed?

**Comment by shenlebantongying** [comment]
We already removed them. We just bring them back to Windows Only.
