### ISSUE TITLE
Qt Multimedia repeat first played sound.

### ISSUE THREAD

**Issue by BEST8OY** [xiaoyifang/goldendict#341]
Hello
In https://github.com/xiaoyifang/goldendict/issues/333 issue you wanted a new issue to be opened for this bug.

I knew this issue for long time, but I thought it's known so I didn't mention this bug so far.
How to reproduce:
1-Set QtMultimedia as audio player in preference audio.
2-Play a pronunciation.
3-From now on any pronunciation you play will be the one which had been played in step 2.

**Comment by xiaoyifang** [comment]
https://github.com/xiaoyifang/goldendict/releases/tag/v23.02.07-alpha.230211.3f4852bb
try this version . I have try a different way to use the qmediaplayer. seems solved the issue.

the weird thing about this issue is that with the previous compiled version  it work on my home PC but not on my office PC.
I guess this bug is caused by Qt+Windows
