### ISSUE TITLE
[help] large memory consumption

### ISSUE THREAD

**Issue by xiaoyifang** [xiaoyifang/goldendict#37]
This is a very rare case,not in emergency .
![image](https://user-images.githubusercontent.com/105986/160873729-a5e80d7f-6bd2-4766-ad61-dbd2647d9588.png)

volunteer from community has found out that when gd has about 1000 dicitonaries .   right click on the dictionary (in dictionary toolbar) to edit the dictionary group .The memory will shoot up to about 9+GB.

First I have doubted about the opened Index file (The indexed file has been hold open during the time),but simple test has show that the memory will not go up if only hold open the index,   

Then I doubt that the Fulltextindex may has affected it .but disable fulltextindex in preference has no effect.

I also doubted about the loaddictionaries process ,which takes place when open the gd.but if there is a memory issue in loaddictionaries's deferredinit , the memory will grow when opened the mainwindow, and will not wait to  grow only when `edit dictionary` action has occured. 

suspected files `editdictionaries.cc`

large amount of dictionaries can be achieved through duplicating the existing dictionaries multi time.

Both detailed investigation and commits are welcome.

**Comment by GPLv3-fan** [comment]
**The same issue happens in Manjaro KDE with the latest QT6 version.** 

I increased the "ulimit" of my OS as suggested on GD forum:
http://goldendict.org/forum/viewtopic.php?f=4&t=1764&p=8663&hilit=ulimit#p8649

Afterwards, I added around 550 dictionaries and GoldenDict QT6 works “apparently” OK. However, after 30-40 minutes, the consumption of memory increases so much that it crashes after looking for a headword. 

Reducing the amount of dictionaries to 300 makes GoldenDict to work with more stability. However, some people really need to have many dictionaries because they have to look words in 4-5 languages. This issue is very important.

**Comment by xiaoyifang** [comment]
> crashes after looking for a headword.

this is another issue.

**Comment by xiaoyifang** [comment]
https://github.com/xiaoyifang/goldendict/blob/5bdce7fc521d3c2b1383f4d6ee6a847476952948/main.cc#L249-L266

is this code related.

**Comment by xiaoyifang** [comment]
> Manjaro KDE

check `ulimit -n` in you computer

**Comment by xiaoyifang** [comment]
when you have more than 500 dictionaries ,what's your normal operations ,can you list them ?
`search words` etc.

**Comment by GPLv3-fan** [comment]
> when you have more than 500 dictionaries ,what's your normal operations ,can you list them ?

Sometimes GD crashes immediately after loading >500 dictionaries and cannot be used. Therefore, I currently have "only" around 400 dictionaries and works fine.  My Ulimit is set at 50.000.000 on Manjaro KDE (latest stable) :

![image](https://user-images.githubusercontent.com/58692066/163718074-4d9610fb-0917-4c1c-9969-45fd837db46f.png)

When I successfully add 520-550 dictionaries, sometimes the program crashes unexpectedly after 20-30 minutes of usage, as follows:

I have 2 virtual desktops. One virtual desktop with Okular (a PDF reader) and another with GoldenDict. I use the “pop-up function” to send words directly to the "main window" of GoldenDict on the other virtual desktop.

I read a PDF and whenever find an unknown word, double-click the word, then click the "Flag" of GoldenDict and the word is sent to the input line on the “main window” of GD.

That process seems to work OK. The only problem is that after 20-30 minutes memory consumption increases and the program closes unexpectedly (automatically).

Please let me know how could I provide more details. This problem is important for people who need to consult dictionaries in > 4-5 languages.

----------
By the way, here you can find a collection of almost 200 GiB in dictionaries for GoldenDict. You can download > 500 dictionaries easily for testing purposes:
https://forum.freemdict.com/t/topic/12050

**Comment by xiaoyifang** [comment]
> whenever find an unknown word, double-click the word, then click the "Flag" of GoldenDict

is this a GD's functionality or the system's ?

**Comment by GPLv3-fan** [comment]
I use the _"Flag"_ feature built-in on GoldenDict for the Scan Popup:

![image](https://user-images.githubusercontent.com/58692066/163738611-01c91508-b4d4-4799-8f19-29ac59e393f1.png)

![image](https://user-images.githubusercontent.com/58692066/163738631-f12b898d-f326-48b1-b0c1-7a1214cd2a02.png)

**Comment by xiaoyifang** [comment]
can you manage to capture a core dump file for analysis
https://blog.xojo.com/2015/08/17/take-a-core-dump-what-to-do-when-your-app-crashes-on-linux/

**Comment by GPLv3-fan** [comment]
Here is a core dump. This time, GD crashed while loading more than 500 dictionaries. I have around 450 dictionaries and everything is OK. When I try to upload more than 500 dictionaries, it crashes. Other times, dictionaries are indexed but after 30 minutes of usafe GD crashes anyway.

 Ulimit is not the reason (> 5 million).

**The terminal points to a "segmentation fault":**

https://mega.nz/file/MtcRRCIJ#LC0yQbB7gvvu37naKW5zBGf4ieYxBlyG6zdHgnWqILM

**Comment by xiaoyifang** [comment]
> Ulimit is not the reason (> 5 million).

`ulimit -c`  is used to enable core dump .   can you upload the output of the command .



> **The terminal points to a "segmentation fault":**
> 
> https://mega.nz/file/MtcRRCIJ#LC0yQbB7gvvu37naKW5zBGf4ieYxBlyG6zdHgnWqILM

the core dump file ,not the log file.

**Comment by GPLv3-fan** [comment]
@xiaoyifang  I finally got the "core dump files" from two different crashes of GoldenDict (Manjaro KDE):

https://send.vis.ee/download/15d9dd886af68c00/#eXHubmDV-nhYnu3ehkAIiA
-----------
PS. The above link is only valid for 7 days or 20 downloads. 
It is a useful service inspired by Mozilla Send: https://github.com/timvisee/send
Please keep it after downloading. I can send more "core dumps" as needed.

**Comment by xiaoyifang** [comment]
anyone who is an expert in analysing core dump is welcome, any idea will be welcome.

I'll need some time to analyze this file.

**Comment by xiaoyifang** [comment]
what's your qt version @GPLv3-fan

**Comment by GPLv3-fan** [comment]
> what's your qt version @GPLv3-fan

**Qt version 5.15.3**
![image](https://user-images.githubusercontent.com/58692066/165745304-77b67678-5654-4228-b856-07fd912417ec.png)

**Comment by xiaoyifang** [comment]
@GPLv3-fan can you check your dictionary folders  settings to see if they appear like this (one folder includes another folder)
```
/A/B/C   
/A/         rescursive
```

**Comment by GPLv3-fan** [comment]
My dictionary folders usually have this structure:
![image](https://user-images.githubusercontent.com/58692066/168454945-ae73b81f-99fb-4592-b53e-b87546ee86f7.png)

![image](https://user-images.githubusercontent.com/58692066/168454956-0119ba73-fdde-4ad2-8fb5-5b34cb917139.png)

I always organize folders by language and subfolders by each specific dictionary. 

Sometimes there are sub-folders within sub-folders, like this case:

![image](https://user-images.githubusercontent.com/58692066/168454987-762291a1-94d7-4e7b-820f-62ce9433f5af.png)

**Comment by xiaoyifang** [comment]
I think the core dump file has strip all the pdb infomation,
is it possible that you build a debug version and try to reproduce the segmental crash.

**Comment by GPLv3-fan** [comment]
>  is it possible that you build a debug version and try to reproduce the segmental crash.

I would like to provide more data but I do not know how to build a debug version on Manjaro.

Maybe other users with technical knowledge could help in the future...

**Comment by xiaoyifang** [comment]
does the crash still existed when dictionaries > 500 ?

**Comment by GPLv3-fan** [comment]
>  does the crash still existed when dictionaries > 500 ?

No, random crashes are uncommon now.

The commits from July/August improved the stability ! Thanks !
