### ISSUE TITLE
Dictionaries pop-up too wide to fit on screen

### ISSUE THREAD

**Issue by homocomputeris** [xiaoyifang/goldendict#397]
It would be great to be able to make the Dictionaries window smaller. It is too wide and for some reason cannot be made smaller using mouse.

<img width="1440" alt="Screenshot 2023-03-18 at 23 10 30" src="https://user-images.githubusercontent.com/7422433/226142956-28c84b40-8261-49b6-a310-dd4a29940b41.png">

**Comment by shenlebantongying** [comment]
I think we should make the "Sources" tab vertical like those apps:

The horizontal tab bar is not scalable.

<img width=400 src="https://user-images.githubusercontent.com/20123683/226162169-b0cded49-c841-4fad-b71c-d68b56505bb1.png">

**Comment by xiaoyifang** [comment]
maybe need to set the minimum and maximum size?

**Comment by shenlebantongying** [comment]
The current minimum size is mainly due to text eliding.

If the window got smaller, some tab text got elided. New users are likely to be more confused because they can only see half of the text, while it is not a problem for old users. (You can check how bad the situation was in screenshots of https://github.com/xiaoyifang/goldendict/pull/267)

If in future we add extra dict types, the tab bar will be even larger. Thus, I think we should use a vertical tab bar.

**Comment by homocomputeris** [comment]
Can the tab bar be arranged in 2 rows in narrow windows?

**Comment by xiaoyifang** [comment]
> If the window got smaller, some tab text will be elided.

this depends on settings.   

when has more tabs ,it should display like this.  maybe another new qt bug in qt6.4.3
![image](https://user-images.githubusercontent.com/105986/226223431-adfe1ef4-ed8d-4d2a-8a18-f06722e965eb.png)

**Comment by xiaoyifang** [comment]
https://github.com/xiaoyifang/goldendict/blob/4008e47625f08fefef40d011d2c297fad06d85cf/sources.ui#L31-L33

**Comment by xiaoyifang** [comment]
change this to true should be ok,need test.

**Comment by shenlebantongying** [comment]
I don't think this is a technical problem. The choice is deliberate. https://github.com/xiaoyifang/goldendict/commit/83fe17a9ce9c501d0ab5de745886b6c076dccb9f

usesScrollButtons is for dynamic number of tabs, like the browser's tab so that when the number grows, some will be hidden.

Here is a static tab where all types of dicts should be discovered in one peek for a first-time users.

I don't think we should add ScrollButtons which will hide some of the dict types. Some really powerful types of dict like "Programs" will never be discovered if they got hidden.

**Comment by xiaoyifang** [comment]
at that time of the commit , the tab count is less .
As we continue to add tabs ,we can remove this restrictions to make it work.

Even we arrange it in vertical ,there will still be chance ,it can not covered by one peek.

a first-time users need to learn:-) ,we do not need to put too much effort on this.

**Comment by shenlebantongying** [comment]
> we do not need to put too much effort on this.

Fine. We can see if someone complains that the tabbar scrolling is too long to scroll and revise this.
